### ISSUE TITLE
Variable names are impossible to read in the debugger variable window

### ISSUE THREAD

**Issue by Konkord360** [gerryhjs/gerry-themes-issue-tracker#1]
In all themes the font color for the variable names in the debugger windows is unreadable.
![image](https://user-images.githubusercontent.com/32643151/190594259-b1748737-127a-4c97-8439-fac73bf71034.png)
The color should be of higher contrast to make it possible to read. It cannot be changed individually by the user, since it is dependent only on the theme.

**Comment by gerryhjs** [comment]
It will fixed in next version and highlight as accent color. Thanks for report. If you have any problem please contact me later.

**Comment by gerryhjs** [comment]
@Konkord360 Solved on version 2022.1.17: https://plugins.jetbrains.com/plugin/19668-gerry-themes-pro/versions/stable/226017
Here is a 3 months freesubscription discount code for you, please contact me at gerryhjs@outlook.com.

**Comment by gerryhjs** [comment]
> @Konkord360 Solved on version 2022.1.17: https://plugins.jetbrains.com/plugin/19668-gerry-themes-pro/versions/stable/226017 Here is a 3 months freesubscription discount code for you, please contact me at [gerryhjs@outlook.com](mailto:gerryhjs@outlook.com).

Please reply me your email here and I will send you the discount code :)
