### ISSUE TITLE
Cannot set Gerry violet theme: unsupported char at 2:active

### ISSUE THREAD

**Issue by abikko** [gerryhjs/gerry-themes-issue-tracker#2]
Trying to switch theme to Gerry Violet/Storm/Oceanic, using free version.
And also getting this error in Android Studio, but all themes changes except editor theme.
<img width="376" alt="Screen Shot 2022-09-21 at 17 34 36" src="https://user-images.githubusercontent.com/54619831/191493800-3fb068b7-b780-4c97-b4b7-7f088333b42c.png">

**Comment by abikko** [comment]
If you need some reports about this bug, also let me know how to provide them.

**Comment by gerryhjs** [comment]
@abikko Could tell me what plugin version your are using ?  I don't use  Android Studio often, but I will test it later.

**Comment by abikko** [comment]
@gerryhjs Hello, also using Gerry Themes Pro, this bug causes both of your themes.
Plugin version for both of plugins: 2022.1.17
Using flutter for dev.

**Comment by gerryhjs** [comment]
I have test Gerry Themes on Android studio and it works fine. 
![截图_jetbrains-studio_20220922105251](https://user-images.githubusercontent.com/45413498/191647774-a7faa1e8-53f0-45e5-bb76-ca0a2a794c13.png)

**Comment by abikko** [comment]
Hm, I have not latest Android Studio version, I will update it, and will report you if problem will exist after update.

**Comment by gerryhjs** [comment]
@abikko Could you test to install other theme plugin if they can work on your Android studio? For example: https://plugins.jetbrains.com/plugin/12102-cyan-light-theme

**Comment by gerryhjs** [comment]
Okay, if you have any problem after upgrade just feel free to contact me later.

**Comment by abikko** [comment]
@gerryhjs Yep, old IDE version causes the problem, closing the issue.
