### ISSUE TITLE
IDE minimise and maximise icons are not visible on hover

### ISSUE THREAD

**Issue by ivanalmasi** [gerryhjs/gerry-themes-issue-tracker#3]
Steps to reproduce:
1. Hover minimise or maximise icon of the IDE

![image](https://user-images.githubusercontent.com/35292893/192149603-1f6554c8-57fa-4ce9-af60-5bf9552a9d8a.png)

![image](https://user-images.githubusercontent.com/35292893/192149626-817d88f7-08f5-46db-81ae-b23b07fed332.png)

**Comment by gerryhjs** [comment]
I won't change icon size in themes. Could you tell me which version IDE you are using? I will test later.

**Comment by gerryhjs** [comment]
@Metalmi I guess you are using 2022.3 EAP? I can't reproduce, please help me to check if it's a problem of plugin. You can change to other theme and check if it is still happened.

**Comment by ivanalmasi** [comment]
@gerryhjs Seems to be related to New UI. It happens also on 2022.2. It works properly on themes created by JetBrains.

**Comment by gerryhjs** [comment]
So I will closed the issue. I can't reproduce here so I cannot report it for you. You can submit a issue to youtrack.

**Comment by gerryhjs** [comment]
@Metalmi I reproduce this issue under Windows 10. I will find out a way to solve it later.

**Comment by gerryhjs** [comment]
@Metalmi I found the problem, it will fix in next version. Thanks for your report, please contact me by email( gerryhjs@outlook.com) and I will send you a 3 month free discount code.

**Comment by ivanalmasi** [comment]
> @Metalmi I found the problem, it will fix in next version. Thanks for your report, please contact me by email( [gerryhjs@outlook.com](mailto:gerryhjs@outlook.com)) and I will send you a 3 month free discount code.

Thanks a lot! 🙂

**Comment by gerryhjs** [comment]
Fixed on version 2022.1.20.patch1

**Comment by gerryhjs** [comment]
> > @Metalmi I found the problem, it will fix in next version. Thanks for your report, please contact me by email( [gerryhjs@outlook.com](mailto:gerryhjs@outlook.com)) and I will send you a 3 month free discount code.
> 
> Thanks a lot! slightly_smiling_face

Please reply me your email here and I will send you the discount code :)

**Comment by ivanalmasi** [comment]
> Please reply me your email here and I will send you the discount code :)

Please send it to *****. Thanks again 🙂

**Comment by gerryhjs** [comment]
@Metalmi Seems it's a Windows issue. I don't use Windows for my daily develop, I only check it on a personal laptop. You can check it after update version 2022.1.20.patch1.

**Comment by ivanalmasi** [comment]
@gerryhjs No problem, I can test it as soon as it's published. How long it usually takes?

**Comment by gerryhjs** [comment]
@Metalmi I already submit it to jetbrains and is now waiting approved. Maybe you can test by download direct link here first:
########

**Comment by ivanalmasi** [comment]
@gerryhjs Confirmed, works fine now 👍 Thanks!

Do I need to reinstall the plugin from the IDE or it will automatically be installed on update?

**Comment by gerryhjs** [comment]
@Metalmi I thought you don't need to reinstall again. Install by direct link and install from IDE is equals. :)  I provide direct link just for help you test without marketplace.

**Comment by ivanalmasi** [comment]
@gerryhjs Ok, thanks, I was not sure how updates go when it was manually installed. Yes, that part is clear, as approvals sometimes take a bit longer. ;)

**Comment by gerryhjs** [comment]
Never mind. If approve takes too much time I can contact Jetbrains to solved it.
