### ISSUE TITLE
Find in file icons and text are not vertically aligned on center

### ISSUE THREAD

**Issue by ivanalmasi** [gerryhjs/gerry-themes-issue-tracker#4]
Steps to reproduce:
1. Click CTRL + F to open find in file

Actual:
![image](https://user-images.githubusercontent.com/35292893/192149710-2e972ade-48c3-47e4-8a08-d7c22c87d330.png)

Expected:
![image](https://user-images.githubusercontent.com/35292893/192149756-15ddac30-7053-4961-87a2-ac102aea3168.png)

**Comment by gerryhjs** [comment]
Hi @Metalmi Are you using Gerry Themes (Pro) With new UI? I know this issue under new UI but I didn't find a way to solve it yet.  Jetbrains Darcula  has same problem. 
![截图_选择区域_20220926103738](https://user-images.githubusercontent.com/45413498/192183027-6842b3ea-922d-44bc-8880-ea95d5df022e.png)
![截图_选择区域_20220926103528](https://user-images.githubusercontent.com/45413498/192182788-3ae145a4-3ccb-484d-9126-d6116235d2ea.png)

**Comment by gerryhjs** [comment]
I have submmit a issue here: https://youtrack.jetbrains.com/issue/IDEA-302439/When-enabled-New-UI-and-select-other-themes-except-dark-find-in-file-icons-and-text-are-not-vertically-aligned-on-center
